# Generated by Django 2.1.7 on 2019-04-24 10:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('weather', models.CharField(max_length=70)),
                ('temp', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mTitle', models.CharField(max_length=256)),
                ('mNative', models.CharField(max_length=256)),
                ('mNickname', models.CharField(max_length=256)),
                ('mDirecors', models.CharField(max_length=256)),
                ('mActors', models.CharField(max_length=256)),
                ('mTime', models.CharField(max_length=256)),
                ('mCountry', models.CharField(max_length=256)),
                ('mType', models.CharField(max_length=256)),
                ('mPoint', models.CharField(max_length=256)),
                ('mComment', models.CharField(max_length=256)),
                ('mFile', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mNO', models.CharField(max_length=32)),
                ('mMark', models.CharField(max_length=256)),
                ('mPrice', models.CharField(max_length=32)),
                ('mNote', models.CharField(max_length=1024)),
                ('mFile', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='taobao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
            ],
            managers=[
                ('bjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
