/*
Navicat MySQL Data Transfer

Source Server         : root
Source Server Version : 50725
Source Host           : localhost:3306
Source Database       : root

Target Server Type    : MYSQL
Target Server Version : 50725
File Encoding         : 65001

Date: 2019-04-25 22:59:14
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for testmodel_movie
-- ----------------------------
DROP TABLE IF EXISTS `testmodel_movie`;
CREATE TABLE `testmodel_movie` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mTitle` varchar(256) NOT NULL,
  `mNative` varchar(256) NOT NULL,
  `mNickname` varchar(256) NOT NULL,
  `mDirecors` varchar(256) NOT NULL,
  `mActors` varchar(256) NOT NULL,
  `mTime` varchar(256) NOT NULL,
  `mCountry` varchar(256) NOT NULL,
  `mType` varchar(256) NOT NULL,
  `mPoint` varchar(256) NOT NULL,
  `mComment` varchar(256) NOT NULL,
  `mFile` varchar(256) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=601 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of testmodel_movie
-- ----------------------------
INSERT INTO `testmodel_movie` VALUES ('351', '肖申克的救赎', '/ The Shawshank Redemption', '/ 月黑高飞(港)  /  刺激1995(台)', '弗兰克·德拉邦特 Frank Darabont', '蒂姆·罗宾斯 Tim Robbins /...', '1994', '美国', '犯罪 剧情', '9.6', '1401550人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p480747492.jpg');
INSERT INTO `testmodel_movie` VALUES ('352', '霸王别姬', '', '/ 再见，我的妾  /  Farewell My Concubine', '陈凯歌 Kaige Chen', '张国荣 Leslie Cheung / 张丰毅 Fengyi Zha...', '1993', '中国大陆 香港', '剧情 爱情 同性', '9.6', '1038128人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910813120.jpg');
INSERT INTO `testmodel_movie` VALUES ('353', '这个杀手不太冷', '/ Léon', '/ 杀手莱昂  /  终极追杀令(台)', '吕克·贝松 Luc Besson', '让·雷诺 Jean Reno / 娜塔莉·波特曼 ...', '1994', '法国', '剧情 动作 犯罪', '9.4', '1279733人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p511118051.jpg');
INSERT INTO `testmodel_movie` VALUES ('354', '阿甘正传', '/ Forrest Gump', '/ 福雷斯特·冈普', '罗伯特·泽米吉斯 Robert Zemeckis', '汤姆·汉克斯 Tom Hanks / ...', '1994', '美国', '剧情 爱情', '9.4', '1103796人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p510876377.jpg');
INSERT INTO `testmodel_movie` VALUES ('355', '美丽人生', '/ La vita è bella', '/ 一个快乐的传说(港)  /  Life Is Beautiful', '罗伯托·贝尼尼 Roberto Benigni', '罗伯托·贝尼尼 Roberto Beni...', '1997', '意大利', '剧情 喜剧 爱情 战争', '9.5', '646317人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p510861873.jpg');
INSERT INTO `testmodel_movie` VALUES ('356', '泰坦尼克号', '/ Titanic', '/ 铁达尼号(港 / 台)', '詹姆斯·卡梅隆 James Cameron', '莱昂纳多·迪卡普里奥 Leonardo...', '1997', '美国', '剧情 爱情 灾难', '9.3', '1044273人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p457760035.jpg');
INSERT INTO `testmodel_movie` VALUES ('357', '千与千寻', '/ 千と千尋の神隠し', '/ 神隐少女(台)  /  Spirited Away', '宫崎骏 Hayao Miyazaki', '柊瑠美 Rumi Hîragi / 入野自由 Miy...', '2001', '日本', '剧情 动画 奇幻', '9.3', '1029533人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1606727862.jpg');
INSERT INTO `testmodel_movie` VALUES ('358', '辛德勒的名单', '/ Schindler\'s List', '/ 舒特拉的名单(港)  /  辛德勒名单', '史蒂文·斯皮尔伯格 Steven Spielberg', '连姆·尼森 Liam Neeson...', '1993', '美国', '剧情 历史 战争', '9.5', '576354人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p492406163.jpg');
INSERT INTO `testmodel_movie` VALUES ('359', '盗梦空间', '/ Inception', '/ 潜行凶间(港)  /  全面启动(台)', '克里斯托弗·诺兰 Christopher Nolan', '莱昂纳多·迪卡普里奥 Le...', '2010', '美国 英国', '剧情 科幻 悬疑 冒险', '9.3', '1109996人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p513344864.jpg');
INSERT INTO `testmodel_movie` VALUES ('360', '忠犬八公的故事', '/ Hachi: A Dog\'s Tale', '/ 忠犬小八(台)  /  秋田犬八千(港)', '莱塞·霍尔斯道姆 Lasse Hallström', '理查·基尔 Richard Ger...', '2009', '美国 英国', '剧情', '9.3', '731581人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p524964016.jpg');
INSERT INTO `testmodel_movie` VALUES ('361', '机器人总动员', '/ WALL·E', '/ 瓦力(台)  /  太空奇兵·威E(港)', '安德鲁·斯坦顿 Andrew Stanton', '本·贝尔特 Ben Burtt / 艾丽...', '2008', '美国', '爱情 科幻 动画 冒险', '9.3', '735345人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1461851991.jpg');
INSERT INTO `testmodel_movie` VALUES ('362', '三傻大闹宝莱坞', '/ 3 Idiots', '/ 三个傻瓜(台)  /  作死不离3兄弟(港)', '拉库马·希拉尼 Rajkumar Hirani', '阿米尔·汗 Aamir Khan / 卡...', '2009', '印度', '剧情 喜剧 爱情 歌舞', '9.2', '996838人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p579729551.jpg');
INSERT INTO `testmodel_movie` VALUES ('363', '海上钢琴师', '/ La leggenda del pianista sull\'oceano', '/ 声光伴我飞(港)  /  一九零零的传奇', '朱塞佩·托纳多雷 Giuseppe Tornatore', '蒂姆·罗斯 Tim Roth / ...', '1998', '意大利', '剧情 音乐', '9.2', '818150人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p511146807.jpg');
INSERT INTO `testmodel_movie` VALUES ('364', '放牛班的春天', '/ Les choristes', '/ 歌声伴我心(港)  /  唱诗班男孩', '克里斯托夫·巴拉蒂 Christophe Barratier', '热拉尔·朱尼奥 Gé...', '2004', '法国 瑞士 德国', '剧情 音乐', '9.3', '690160人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910824951.jpg');
INSERT INTO `testmodel_movie` VALUES ('365', '楚门的世界', '/ The Truman Show', '/ 真人Show(港)  /  真人戏', '彼得·威尔 Peter Weir', '金·凯瑞 Jim Carrey / 劳拉·琳妮 Lau...', '1998', '美国', '剧情 科幻', '9.2', '762482人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p479682972.jpg');
INSERT INTO `testmodel_movie` VALUES ('366', '大话西游之大圣娶亲', '/ 西遊記大結局之仙履奇緣', '/ 西游记完结篇仙履奇缘  /  齐天大圣西游记', '刘镇伟 Jeffrey Lau', '周星驰 Stephen Chow / 吴孟达 Man Tat Ng...', '1995', '香港 中国大陆', '喜剧 爱情 奇幻 古装', '9.2', '771266人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2455050536.jpg');
INSERT INTO `testmodel_movie` VALUES ('367', '星际穿越', '/ Interstellar', '/ 星际启示录(港)  /  星际效应(台)', '克里斯托弗·诺兰 Christopher Nolan', '马修·麦康纳 Matthew Mc...', '2014', '美国 英国 加拿大 冰岛', '剧情 科幻 冒险', '9.2', '791518人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2206088801.jpg');
INSERT INTO `testmodel_movie` VALUES ('368', '龙猫', '/ となりのトトロ', '/ 邻居托托罗  /  邻家的豆豆龙', '宫崎骏 Hayao Miyazaki', '日高法子 Noriko Hidaka / 坂本千夏 Ch...', '1988', '日本', '动画 奇幻 冒险', '9.2', '681728人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.jpg');
INSERT INTO `testmodel_movie` VALUES ('369', '教父', '/ The Godfather', '/ Mario Puzo\'s The Godfather', '弗朗西斯·福特·科波拉 Francis Ford Coppola', '马龙·白兰度 M...', '1972', '美国', '剧情 犯罪', '9.3', '500179人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p616779645.jpg');
INSERT INTO `testmodel_movie` VALUES ('370', '熔炉', '/ 도가니', '/ 无声呐喊(港)  /  漩涡', '黄东赫 Dong-hyuk Hwang', '孔侑 Yoo Gong / 郑有美 Yu-mi Jeong ...', '2011', '韩国', '剧情', '9.3', '446123人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1363250216.jpg');
INSERT INTO `testmodel_movie` VALUES ('371', '无间道', '/ 無間道', '/ Infernal Affairs  /  Mou gaan dou', '刘伟强 / 麦兆辉', '刘德华 / 梁朝伟 / 黄秋生', '2002', '香港', '剧情 犯罪 悬疑', '9.1', '633194人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2233971046.jpg');
INSERT INTO `testmodel_movie` VALUES ('372', '疯狂动物城', '/ Zootopia', '/ 优兽大都会(港)  /  动物方城市(台)', '拜伦·霍华德 Byron Howard / 瑞奇·摩尔 Rich Moore', '金妮弗·...', '2016', '美国', '喜剧 动画 冒险', '9.2', '869405人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2315672647.jpg');
INSERT INTO `testmodel_movie` VALUES ('373', '当幸福来敲门', '/ The Pursuit of Happyness', '/ 寻找快乐的故事(港)  /  追求快乐', '加布里尔·穆奇诺 Gabriele Muccino', '威尔·史密斯 Will Smith ...', '2006', '美国', '剧情 传记 家庭', '9.0', '806657人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1312700744.jpg');
INSERT INTO `testmodel_movie` VALUES ('374', '怦然心动', '/ Flipped', '/ 萌动青春  /  青春萌动', '罗伯·莱纳 Rob Reiner', '玛德琳·卡罗尔 Madeline Carroll / 卡...', '2010', '美国', '剧情 喜剧 爱情', '9.0', '890896人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p663036666.jpg');
INSERT INTO `testmodel_movie` VALUES ('375', '触不可及', '/ Intouchables', '/ 闪亮人生(港)  /  逆转人生(台)', '奥利维·那卡什 Olivier Nakache / 艾力克·托兰达 Eric Toledano   主..', ': 奥利维·那卡什 Olivier Nakache / 艾力克·托兰达 Eric Toledano   主...', '2011', '法国', '剧情 喜剧', '9.2', '533224人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1454261925.jpg');
INSERT INTO `testmodel_movie` VALUES ('376', '蝙蝠侠：黑暗骑士', '/ The Dark Knight', '/ 蝙蝠侠前传2：黑暗骑士  /  黑暗骑士(台)', '克里斯托弗·诺兰 Christopher Nolan', '克里斯蒂安·贝尔 Christ...', '2008', '美国 英国', '剧情 动作 科幻 犯罪 惊悚', '9.1', '514505人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p462657443.jpg');
INSERT INTO `testmodel_movie` VALUES ('377', '乱世佳人', '/ Gone with the Wind', '/ 飘', '维克多·弗莱明 Victor Fleming / 乔治·库克 George Cukor', '费...', '1939', '美国', '剧情 历史 爱情 战争', '9.2', '371075人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1963126880.jpg');
INSERT INTO `testmodel_movie` VALUES ('378', '活着', '', '/ 人生  /  Lifetimes', '张艺谋 Yimou Zhang', '葛优 You Ge / 巩俐 Li Gong / 姜武 Wu Jiang', '1994', '中国大陆 香港', '剧情 历史 家庭', '9.2', '412184人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2513253791.jpg');
INSERT INTO `testmodel_movie` VALUES ('379', '少年派的奇幻漂流', '/ Life of Pi', '/ 少年Pi的奇幻漂流  /  漂流少年Pi', '李安 Ang Lee', '苏拉·沙玛 Suraj Sharma / 伊尔凡·可汗 Irrfan...', '2012', '美国 台湾 英国 加拿大', '剧情 奇幻 冒险', '9.0', '805173人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1784592701.jpg');
INSERT INTO `testmodel_movie` VALUES ('380', '控方证人', '/ Witness for the Prosecution', '/ 雄才伟略  /  情妇', '比利·怀尔德 Billy Wilder', '泰隆·鲍华 Tyrone Power / 玛琳·...', '1957', '美国', '剧情 犯罪 悬疑', '9.6', '176960人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1505392928.jpg');
INSERT INTO `testmodel_movie` VALUES ('381', '天堂电影院', '/ Nuovo Cinema Paradiso', '/ 星光伴我心(港)  /  新天堂乐园(台)', '朱塞佩·托纳多雷 Giuseppe Tornatore', '安东内拉·阿蒂利 Anton...', '1988', '意大利 法国', '剧情 爱情', '9.2', '398441人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910901025.jpg');
INSERT INTO `testmodel_movie` VALUES ('382', '鬼子来了', '', '/ Devils on the Doorstep', '姜文 Wen Jiang', '姜文 Wen Jiang / 香川照之 Teruyuki Kagawa /...', '2000', '中国大陆', '剧情 历史 战争', '9.2', '336803人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p776573640.jpg');
INSERT INTO `testmodel_movie` VALUES ('383', '指环王3：王者无敌', '/ The Lord of the Rings: The Return of the King', '/ 魔戒三部曲：王者再临(台 / 港)', '彼得·杰克逊 Peter Jackson', '维果·莫腾森 Viggo Mortensen / ...', '2003', '美国 新西兰', '剧情 动作 奇幻 冒险', '9.1', '404170人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910825503.jpg');
INSERT INTO `testmodel_movie` VALUES ('384', '十二怒汉', '/ 12 Angry Men', '/ 12怒汉  /  十二怒汉', 'Sidney Lumet', '亨利·方达 Henry Fonda / 马丁·鲍尔萨姆 Marti...', '1957', '美国', '剧情', '9.4', '239770人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2173577632.jpg');
INSERT INTO `testmodel_movie` VALUES ('385', '天空之城', '/ 天空の城ラピュタ', '/ Tenkû no shiro Rapyuta  /  Laputa: Castle in the Sky', '宫崎骏 Hayao Miyazaki', '田中真弓 Mayumi Tanaka / 横泽启子 Ke...', '1986', '日本', '动画 奇幻 冒险', '9.1', '473295人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1446261379.jpg');
INSERT INTO `testmodel_movie` VALUES ('386', '摔跤吧！爸爸', '/ Dangal', '/ 我和我的冠军女儿(台)  /  打死不离3父女(港)', '涅提·蒂瓦里 Nitesh Tiwari', '阿米尔·汗 Aamir Khan / 法缇玛...', '2016', '印度', '剧情 传记 运动 家庭', '9.0', '771321人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2457983084.jpg');
INSERT INTO `testmodel_movie` VALUES ('387', '飞屋环游记', '/ Up', '/ 冲天救兵(港)  /  天外奇迹(台)', '彼特·道格特 Pete Docter / 鲍勃·彼德森 Bob Peterson', '爱德...', '2009', '美国', '剧情 喜剧 动画 冒险', '8.9', '720792人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p485887754.jpg');
INSERT INTO `testmodel_movie` VALUES ('388', '大话西游之月光宝盒', '/ 西遊記第壹佰零壹回之月光寶盒', '/ 西游记101回月光宝盒  /  齐天大圣东游记', '刘镇伟 Jeffrey Lau', '周星驰 Stephen Chow / 吴孟达 Man Tat Ng...', '1995', '香港 中国大陆', '喜剧 爱情 奇幻 古装', '9.0', '622692人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1280323646.jpg');
INSERT INTO `testmodel_movie` VALUES ('389', '搏击俱乐部', '/ Fight Club', '/ 搏击会(港)  /  斗阵俱乐部(台)', '大卫·芬奇 David Fincher', '爱德华·诺顿 Edward Norton / 布拉...', '1999', '美国 德国', '剧情 动作 悬疑 惊悚', '9.0', '516856人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1910926158.jpg');
INSERT INTO `testmodel_movie` VALUES ('390', '罗马假日', '/ Roman Holiday', '/ 金枝玉叶(港)  /  罗马假期(台)', '威廉·惠勒 William Wyler', '奥黛丽·赫本 Audrey Hepburn / 格...', '1953', '美国', '喜剧 剧情 爱情', '9.0', '539333人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2189265085.jpg');
INSERT INTO `testmodel_movie` VALUES ('391', '哈尔的移动城堡', '/ ハウルの動く城', '/ 呼啸山城  /  霍尔的移动城堡', '宫崎骏 Hayao Miyazaki', '倍赏千惠子 Chieko Baishô / 木村拓...', '2004', '日本', '动画 奇幻 冒险', '9.0', '523382人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2174346180.jpg');
INSERT INTO `testmodel_movie` VALUES ('392', '闻香识女人', '/ Scent of a Woman', '/ 女人香  /  女人的芳香', '马丁·布莱斯 Martin Brest', '阿尔·帕西诺 Al Pacino / 克里斯...', '1992', '美国', '剧情', '9.0', '461014人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2550757929.jpg');
INSERT INTO `testmodel_movie` VALUES ('393', '辩护人', '/ 변호인', '/ 逆权大状(港)  /  正义辩护人(台)', '杨宇硕 Woo-seok Yang', '宋康昊 Kang-ho Song / 吴达洙 Dal-su O...', '2013', '韩国', '剧情', '9.2', '318608人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2158166535.jpg');
INSERT INTO `testmodel_movie` VALUES ('394', '窃听风暴', '/ Das Leben der Anderen', '/ 窃听者(港)  /  他人的生活', '弗洛里安·亨克尔·冯·多纳斯马尔克 Florian Henckel von Donnersmarck  &n..', ': 弗洛里安·亨克尔·冯·多纳斯马尔克 Florian Henckel von Donnersmarck  &n...', '2006', '德国', '剧情 悬疑', '9.1', '320063人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1808872109.jpg');
INSERT INTO `testmodel_movie` VALUES ('395', '末代皇帝', '/ The Last Emperor', '/ 末代皇帝溥仪(港)', '贝纳尔多·贝托鲁奇 Bernardo Bertolucci', '尊龙 John Lone / 陈...', '1987', '英国 意大利 中国大陆 法国 美国', '剧情 传记 历史', '9.1', '312782人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p452089833.jpg');
INSERT INTO `testmodel_movie` VALUES ('396', '两杆大烟枪', '/ Lock, Stock and Two Smoking Barrels', '/ 够姜四小强(港)  /  两根枪管(台)', 'Guy Ritchie', 'Jason Flemyng / Dexter Fletcher / Nick Moran', '1998', '英国', '剧情 喜剧 犯罪', '9.1', '353799人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p792443418.jpg');
INSERT INTO `testmodel_movie` VALUES ('397', '飞越疯人院', '/ One Flew Over the Cuckoo\'s Nest', '/ 飞越杜鹃窝(台)  /  飞越喜鹊巢', '米洛斯·福尔曼 Miloš Forman', '杰克·尼科尔森 Jack Nichols...', '1975', '美国', '剧情', '9.1', '356556人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p792238287.jpg');
INSERT INTO `testmodel_movie` VALUES ('398', '死亡诗社', '/ Dead Poets Society', '/ 暴雨骄阳(港)  /  春风化雨(台)', '彼得·威尔 Peter Weir', '罗宾·威廉姆斯 Robin Williams / 罗伯...', '1989', '美国', '剧情', '9.0', '390986人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910824340.jpg');
INSERT INTO `testmodel_movie` VALUES ('399', '素媛', '/ 소원', '/ 许愿  /  希望：为爱重生(台)', '李濬益 Jun-ik Lee', '薛景求 Kyung-gu Sol / 严志媛 Ji-won Uhm ...', '2013', '韩国', '剧情', '9.2', '289010人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2118532944.jpg');
INSERT INTO `testmodel_movie` VALUES ('400', '寻梦环游记', '/ Coco', '/ 可可夜总会(台)  /  玩转极乐园(港)', '李·昂克里奇 Lee Unkrich / 阿德里安·莫利纳 Adrian Molina', '...', '2017', '美国', '喜剧 动画 奇幻 音乐', '9.0', '735662人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2503997609.jpg');
INSERT INTO `testmodel_movie` VALUES ('401', '指环王2：双塔奇兵', '/ The Lord of the Rings: The Two Towers', '/ 魔戒二部曲：双城奇谋  /  指环王II：双塔', '彼得·杰克逊 Peter Jackson', '伊利亚·伍德 Elijah Wood / 西恩...', '2002', '美国 新西兰', '剧情 动作 奇幻 冒险', '9.0', '379538人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p909265336.jpg');
INSERT INTO `testmodel_movie` VALUES ('402', '教父2', '/ The Godfather: Part Ⅱ', '/ 教父续集  /  教父II', '弗朗西斯·福特·科波拉 Francis Ford Coppola', '阿尔·帕西诺 A...', '1974', '美国', '剧情 犯罪', '9.2', '271200人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2194138787.jpg');
INSERT INTO `testmodel_movie` VALUES ('403', 'V字仇杀队', '/ V for Vendetta', '/ V煞(港)  /  V怪客(台)', '詹姆斯·麦克特格 James McTeigue', '娜塔莉·波特曼 Natalie Por...', '2005', '美国 英国 德国', '剧情 动作 科幻 惊悚', '8.9', '597068人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1465235231.jpg');
INSERT INTO `testmodel_movie` VALUES ('404', '指环王1：魔戒再现', '/ The Lord of the Rings: The Fellowship of the Ring', '/ 魔戒首部曲：魔戒现身  /  指环王I：护戒使者', '彼得·杰克逊 Peter Jackson', '伊利亚·伍德 Elijah Wood / 西恩...', '2001', '新西兰 美国', '剧情 动作 奇幻 冒险', '9.0', '425515人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1354436051.jpg');
INSERT INTO `testmodel_movie` VALUES ('405', '海豚湾', '/ The Cove', '/ 血色海湾(台)  /  海湾', '路易·西霍尤斯 Louie Psihoyos', 'Richard O\'Barry / 路易·西霍...', '2009', '美国', '纪录片', '9.3', '235129人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p455222172.jpg');
INSERT INTO `testmodel_movie` VALUES ('406', '饮食男女', '/ 飲食男女', '/ Eat Drink Man Woman', '李安 Ang Lee', '郎雄 Sihung Lung / 杨贵媚 Kuei-Mei Yang / 吴...', '1994', '台湾 美国', '剧情 家庭', '9.1', '291779人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910899751.jpg');
INSERT INTO `testmodel_movie` VALUES ('407', '狮子王', '/ The Lion King', '/ 狮子王3D', 'Roger Allers / 罗伯·明可夫 Rob Minkoff', '乔纳森·泰勒·托马...', '1994', '美国', '剧情 动画 冒险 歌舞 家庭', '9.0', '404755人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p726659067.jpg');
INSERT INTO `testmodel_movie` VALUES ('408', '美丽心灵', '/ A Beautiful Mind', '/ 有你终生美丽(港)  /  美丽境界(台)', '朗·霍华德 Ron Howard', '罗素·克劳 Russell Crowe / 艾德·哈...', '2001', '美国', '传记 剧情', '8.9', '414640人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1665997400.jpg');
INSERT INTO `testmodel_movie` VALUES ('409', '情书', '/ Love Letter', '/ When I Close My Eyes  /  Letters of Love', '岩井俊二 Shunji Iwai', '中山美穗 Miho Nakayama / 丰川悦司 Ets...', '1995', '日本', '剧情 爱情', '8.9', '515351人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p449897379.jpg');
INSERT INTO `testmodel_movie` VALUES ('410', '钢琴家', '/ The Pianist', '/ 战地琴声(台)  /  战地琴人', '罗曼·波兰斯基 Roman Polanski', '艾德里安·布洛迪 Adrien Brod...', '2002', '法国 德国 英国 波兰', '剧情 传记 历史 战争 音乐', '9.1', '273462人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p792484461.jpg');
INSERT INTO `testmodel_movie` VALUES ('411', '本杰明·巴顿奇事', '/ The Curious Case of Benjamin Button', '/ 奇幻逆缘(港)  /  班杰明的奇幻旅程(台)', '大卫·芬奇 David Fincher', '凯特·布兰切特 Cate Blanchett / ...', '2008', '美国', '剧情 爱情 奇幻', '8.8', '540992人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2192535722.jpg');
INSERT INTO `testmodel_movie` VALUES ('412', '美国往事', '/ Once Upon a Time in America', '/ 四海兄弟(台)  /  义薄云天(港)', '赛尔乔·莱翁内 Sergio Leone', '罗伯特·德尼罗 Robert De Niro ...', '1984', '意大利 美国', '犯罪 剧情', '9.1', '234245人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p477229647.jpg');
INSERT INTO `testmodel_movie` VALUES ('413', '看不见的客人', '/ Contratiempo', '/ 佈局(台)  /  死无对证(港)', '奥里奥尔·保罗 Oriol Paulo', '马里奥·卡萨斯 Mario Casas / 阿...', '2016', '西班牙', '剧情 犯罪 悬疑 惊悚', '8.8', '576899人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2498971355.jpg');
INSERT INTO `testmodel_movie` VALUES ('414', '黑客帝国', '/ The Matrix', '/ 廿二世纪杀人网络(港)  /  骇客任务(台)', '安迪·沃卓斯基 Andy Wachowski / 拉娜·沃卓斯基 Lana Wachowski   主..', ': 安迪·沃卓斯基 Andy Wachowski / 拉娜·沃卓斯基 Lana Wachowski   主...', '1999', '美国 澳大利亚', '动作 科幻', '8.9', '404544人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p451926968.jpg');
INSERT INTO `testmodel_movie` VALUES ('415', '小鞋子', '/ بچههای آسمان', '/ 天堂的孩子  /  小童鞋', '马基德·马基迪 Majid Majidi', '法拉赫阿米尔·哈什米安 Amir Fa...', '1997', '伊朗', '剧情 儿童 家庭', '9.2', '200854人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2165511465.jpg');
INSERT INTO `testmodel_movie` VALUES ('416', '西西里的美丽传说', '/ Malèna', '/ 真爱伴我行(台)  /  玛莲娜', '朱塞佩·托纳多雷 Giuseppe Tornatore', '莫妮卡·贝鲁奇 Monica ...', '2000', '意大利 美国', '剧情 战争 情色', '8.8', '512413人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p792400696.jpg');
INSERT INTO `testmodel_movie` VALUES ('417', '大闹天宫', '', '/ 大闹天宫 上下集  /  The Monkey King', '万籁鸣 Laiming Wan / 唐澄 Cheng  Tang', '邱岳峰 Yuefeng Qiu /...', '1961(中国大陆)', '1964(中国大陆)', '1978(中国大陆)', '9.3', '167918人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2184505167.jpg');
INSERT INTO `testmodel_movie` VALUES ('418', '哈利·波特与魔法石', '/ Harry Potter and the Sorcerer\'s Stone', '/ 哈利波特1：神秘的魔法石(港 / 台)', 'Chris Columbus', 'Daniel Radcliffe / Emma Watson / Rupert Grint', '2001', '美国 英国', '奇幻 冒险', '8.9', '424900人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p804947166.jpg');
INSERT INTO `testmodel_movie` VALUES ('419', '让子弹飞', '', '/ 让子弹飞一会儿  /  火烧云', '姜文 Wen Jiang', '姜文 Wen Jiang / 葛优 You Ge / 周润发 Yun-F...', '2010', '中国大陆 香港', '剧情 喜剧 动作 西部', '8.7', '881897人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1512562287.jpg');
INSERT INTO `testmodel_movie` VALUES ('420', '拯救大兵瑞恩', '/ Saving Private Ryan', '/ 雷霆救兵(港)  /  抢救雷恩大兵(台)', '史蒂文·斯皮尔伯格 Steven Spielberg', '汤姆·汉克斯 Tom Hanks...', '1998', '美国', '剧情 历史 战争', '8.9', '344985人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1014542496.jpg');
INSERT INTO `testmodel_movie` VALUES ('421', '致命魔术', '/ The Prestige', '/ 顶尖对决(台)  /  死亡魔法(港)', '克里斯托弗·诺兰 Christopher Nolan', '休·杰克曼 Hugh Jackman...', '2006', '美国 英国', '剧情 悬疑 惊悚', '8.8', '469597人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p480383375.jpg');
INSERT INTO `testmodel_movie` VALUES ('422', '七宗罪', '/ Se7en', '/ 火线追缉令(台)  /  7宗罪', '大卫·芬奇 David Fincher', '摩根·弗里曼 Morgan Freeman / 布...', '1995', '美国', '剧情 犯罪 悬疑 惊悚', '8.8', '563347人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p457631605.jpg');
INSERT INTO `testmodel_movie` VALUES ('423', '被嫌弃的松子的一生', '/ 嫌われ松子の一生', '/ 花样奇缘(港)  /  令人讨厌的松子的一生(台)', '中岛哲也 Tetsuya Nakashima', '中谷美纪 Miki Nakatani / 瑛太 E...', '2006', '日本', '剧情 歌舞', '8.9', '416875人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p453723669.jpg');
INSERT INTO `testmodel_movie` VALUES ('424', '音乐之声', '/ The Sound of Music', '/ 仙乐飘飘处处闻(港)  /  真善美(台)', '罗伯特·怀斯 Robert Wise', '朱莉·安德鲁斯 Julie Andrews / 克...', '1965', '美国', '剧情 传记 爱情 歌舞', '9.0', '317259人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p453788577.jpg');
INSERT INTO `testmodel_movie` VALUES ('425', '低俗小说', '/ Pulp Fiction', '/ 黑色追緝令(台)  /  危险人物(港)', '昆汀·塔伦蒂诺 Quentin Tarantino', '约翰·特拉沃尔塔 John Tra...', '1994', '美国', '剧情 喜剧 犯罪', '8.8', '463300人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910902213.jpg');
INSERT INTO `testmodel_movie` VALUES ('426', '沉默的羔羊', '/ The Silence of the Lambs', '/ 沉默的羔羊', '乔纳森·戴米 Jonathan Demme', '朱迪·福斯特 Jodie Foster / 安...', '1991', '美国', '剧情 犯罪 惊悚', '8.8', '469086人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1593414327.jpg');
INSERT INTO `testmodel_movie` VALUES ('427', '天使爱美丽', '/ Le fabuleux destin d\'Amélie Poulain', '/ 艾蜜莉的异想世界(台)  /  天使艾米莉', '让-皮埃尔·热内 Jean-Pierre Jeunet', '奥黛丽·塔图 Audrey Tau...', '2001', '法国 德国', '喜剧 爱情', '8.7', '626205人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p803896904.jpg');
INSERT INTO `testmodel_movie` VALUES ('428', '猫鼠游戏', '/ Catch Me If You Can', '/ 逍遥法外  /  神鬼交锋(台)', '史蒂文·斯皮尔伯格 Steven Spielberg', '莱昂纳多·迪卡普里奥 L...', '2002', '美国 加拿大', '传记 犯罪 剧情', '8.9', '362526人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p453924541.jpg');
INSERT INTO `testmodel_movie` VALUES ('429', '勇敢的心', '/ Braveheart', '/ 惊世未了缘(港)  /  梅尔吉勃逊之英雄本色(台)', '梅尔·吉布森 Mel Gibson', '梅尔·吉布森 Mel Gibson / 苏菲·玛...', '1995', '美国', '动作 传记 剧情 历史 战争', '8.9', '371516人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1374546770.jpg');
INSERT INTO `testmodel_movie` VALUES ('430', '蝴蝶效应', '/ The Butterfly Effect', '/ 蝴蝶效应', '埃里克·布雷斯 Eric Bress / J·麦基·格鲁伯 J. Mackye Gruber   主..', ': 埃里克·布雷斯 Eric Bress / J·麦基·格鲁伯 J. Mackye Gruber   主...', '2004', '美国 加拿大', '剧情 悬疑 科幻 惊悚', '8.7', '516470人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2209066019.jpg');
INSERT INTO `testmodel_movie` VALUES ('431', '剪刀手爱德华', '/ Edward Scissorhands', '/ 幻海奇缘(港)  /  剪刀手爱德华', '蒂姆·波顿 Tim Burton', '约翰尼·德普 Johnny Depp / 薇诺娜·...', '1990', '美国', '剧情 奇幻 爱情', '8.7', '640993人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p480956937.jpg');
INSERT INTO `testmodel_movie` VALUES ('432', '春光乍泄', '/ 春光乍洩', '/ 一起快乐  /  Happy Together', '王家卫 Kar Wai Wong', '张国荣 Leslie Cheung / 梁朝伟 Tony Leu...', '1997', '香港 日本 韩国', '剧情 爱情 同性', '8.9', '344046人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p465939041.jpg');
INSERT INTO `testmodel_movie` VALUES ('433', '心灵捕手', '/ Good Will Hunting', '/ 骄阳似我(港)  /  心灵捕手', '格斯·范·桑特 Gus Van Sant', '马特·达蒙 Matt Damon / 罗宾·...', '1997', '美国', '剧情', '8.8', '376946人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p480965695.jpg');
INSERT INTO `testmodel_movie` VALUES ('434', '禁闭岛', '/ Shutter Island', '/ 不赦岛(港)  /  隔离岛(台)', 'Martin Scorsese', '莱昂纳多·迪卡普里奥 Leonardo DiCaprio / ...', '2010', '美国', '剧情 悬疑 惊悚', '8.7', '502635人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1832875827.jpg');
INSERT INTO `testmodel_movie` VALUES ('435', '布达佩斯大饭店', '/ The Grand Budapest Hotel', '/ 布达佩斯大酒店(港)  /  欢迎来到布达佩斯大饭店(台)', '韦斯·安德森 Wes Anderson', '拉尔夫·费因斯 Ralph Fiennes / ...', '2014', '美国 德国 英国', '剧情 喜剧 冒险', '8.8', '465357人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2178872593.jpg');
INSERT INTO `testmodel_movie` VALUES ('436', '穿条纹睡衣的男孩', '/ The Boy in the Striped Pajamas', '/ 穿条纹衣服的男孩  /  穿条纹衣的男孩', '马克·赫尔曼 Mark Herman', '阿萨·巴特菲尔德 Asa Butterfield ...', '2008', '英国 美国', '剧情 战争', '9.0', '231006人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1473670352.jpg');
INSERT INTO `testmodel_movie` VALUES ('437', '入殓师', '/ おくりびと', '/ 礼仪师之奏鸣曲(港)  /  礼仪师(台)', '泷田洋二郎 Yôjirô Takita', '本木雅弘 Masahiro Motoki / ...', '2008', '日本', '剧情', '8.8', '387627人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p594972928.jpg');
INSERT INTO `testmodel_movie` VALUES ('438', '阿凡达', '/ Avatar', '/ 天神下凡(港)  /  化身', '詹姆斯·卡梅隆 James Cameron', '萨姆·沃辛顿 Sam Worthington ...', '2009', '美国 英国', '动作 战争 科幻 冒险', '8.7', '737362人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2180085848.jpg');
INSERT INTO `testmodel_movie` VALUES ('439', '幽灵公主', '/ もののけ姫', '/ 魔法公主  /  幽灵少女', '宫崎骏 Hayao Miyazaki', '松田洋治 Yôji Matsuda / 石田百合...', '1997', '日本', '动画 奇幻 冒险', '8.8', '315796人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1613191025.jpg');
INSERT INTO `testmodel_movie` VALUES ('440', '阳光灿烂的日子', '', '/ In the Heat of the Sun', '姜文 Wen Jiang', '夏雨 Yu Xia / 宁静 Jing Ning / 陶虹 Hong Tao', '1994', '中国大陆 香港', '剧情 爱情', '8.8', '361067人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p967457079.jpg');
INSERT INTO `testmodel_movie` VALUES ('441', '致命ID', '/ Identity', '/ 杀人游戏  /  致命身份', 'James Mangold', 'John Cusack / Ray Liotta / Amanda Peet', '2003', '美国', '剧情 悬疑 惊悚', '8.7', '430266人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p453720880.jpg');
INSERT INTO `testmodel_movie` VALUES ('442', '第六感', '/ The Sixth Sense', '/ 灵异第六感  /  鬼眼', 'M·奈特·沙马兰 M. Night Shyamalan', '布鲁斯·威利斯 Bruce Wi...', '1999', '美国', '剧情 悬疑 惊悚', '8.8', '309464人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2220184425.jpg');
INSERT INTO `testmodel_movie` VALUES ('443', '加勒比海盗', '/ Pirates of the Caribbean: The Curse of the Black Pearl', '/ 加勒比海盗1：黑珍珠号的诅咒  /  神鬼奇航：鬼盗船魔咒(台)', '戈尔·维宾斯基 Gore Verbinski', '约翰尼·德普 Johnny Depp / ...', '2003', '美国', '动作 冒险 奇幻', '8.7', '485123人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1596085504.jpg');
INSERT INTO `testmodel_movie` VALUES ('444', '狩猎', '/ Jagten', '/ 谎言的烙印(台)  /  诬网(港)', '托马斯·温特伯格 Thomas Vinterberg', '麦斯·米科尔森 Mads Mik...', '2012', '丹麦 瑞典', '剧情', '9.1', '185589人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1546987967.jpg');
INSERT INTO `testmodel_movie` VALUES ('445', '断背山', '/ Brokeback Mountain', '/ 断臂山  /  BBM', '李安 Ang Lee', '希斯·莱杰 Heath Ledger / 杰克·吉伦哈尔 Jake...', '2005', '美国 加拿大', '剧情 爱情 同性 家庭', '8.7', '425029人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p513535588.jpg');
INSERT INTO `testmodel_movie` VALUES ('446', '玛丽和马克思', '/ Mary and Max', '/ 巧克力情缘(台)  /  同是天涯寂寞客', '亚当·艾略特 Adam Elliot', '托妮·科莱特 Toni Collette / 菲利...', '2009', '澳大利亚', '剧情 喜剧 动画', '8.9', '279268人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1820615077.jpg');
INSERT INTO `testmodel_movie` VALUES ('447', '重庆森林', '/ 重慶森林', '/ Chungking Express', '王家卫 Kar Wai Wong', '林青霞 Brigitte Lin / 金城武 Takeshi K...', '1994', '香港', '剧情 爱情', '8.7', '442891人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p792381411.jpg');
INSERT INTO `testmodel_movie` VALUES ('448', '摩登时代', '/ Modern Times', '/ The Masses  /  Temps modernes, Les', '查理·卓别林 Charles Chaplin', '查理·卓别林 Charles Chaplin ...', '1936', '美国', '剧情 喜剧 爱情', '9.2', '135740人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2173707976.jpg');
INSERT INTO `testmodel_movie` VALUES ('449', '喜剧之王', '/ 喜劇之王', '/ King of Comedy', '周星驰 Stephen Chow / 李力持 Lik-Chi Lee', '周星驰 Stephen Ch...', '1999', '香港', '喜剧 剧情 爱情', '8.7', '473398人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1043597424.jpg');
INSERT INTO `testmodel_movie` VALUES ('450', '告白', '', '/ 自白  /  母亲', '中岛哲也 Tetsuya Nakashima', '松隆子 Takako Matsu / 冈田将生 ...', '2010', '日本', '剧情 惊悚', '8.7', '444423人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p689520756.jpg');
INSERT INTO `testmodel_movie` VALUES ('451', '大鱼', '/ Big Fish', '/ 大鱼奇缘(港)  /  大智若鱼(台)', '蒂姆·波顿 Tim Burton', '伊万·麦克格雷格 Ewan McGregor / 阿...', '2003', '美国', '剧情 家庭 奇幻 冒险', '8.8', '329233人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p692813374.jpg');
INSERT INTO `testmodel_movie` VALUES ('452', '消失的爱人', '/ Gone Girl', '/ 失踪的女孩  /  失踪女孩', '大卫·芬奇 David Fincher', '本·阿弗莱克 Ben Affleck / 罗莎蒙...', '2014', '美国', '剧情 犯罪 悬疑 惊悚', '8.7', '493119人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2221768894.jpg');
INSERT INTO `testmodel_movie` VALUES ('453', '一一', '', '/ Yi yi  /  Yi yi: A One and a Two', '杨德昌 Edward Yang', '吴念真 / 李凯莉 Kelly Lee / 金燕玲 Elai...', '2000', '台湾 日本', '剧情 爱情 家庭', '9.0', '200328人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2119675128.jpg');
INSERT INTO `testmodel_movie` VALUES ('454', '射雕英雄传之东成西就', '/ 射鵰英雄傳之東成西就', '/ 东成西就  /  大英雄 (日本)', '刘镇伟 Jeffrey Lau', '梁朝伟 Tony Leung Chiu Wai / 林青霞 Bri...', '1993', '香港', '喜剧 奇幻 武侠 古装', '8.7', '363595人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2535922598.jpg');
INSERT INTO `testmodel_movie` VALUES ('455', '阳光姐妹淘', '/ 써니', '/ 阳光姊妹淘(港)  /  桑尼', '姜炯哲 Hyeong-Cheol Kang', '沈恩京 Eun-kyung Shim / 闵孝琳 Hy...', '2011', '韩国', '剧情 喜剧', '8.8', '355937人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1374786017.jpg');
INSERT INTO `testmodel_movie` VALUES ('456', '甜蜜蜜', '', '/ Comrades: Almost a Love Story', '陈可辛 Peter Chan', '黎明 Leon Lai / 张曼玉 Maggie Cheung / ...', '1996', '香港', '剧情 爱情', '8.8', '293052人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1962839732.jpg');
INSERT INTO `testmodel_movie` VALUES ('457', '爱在黎明破晓前', '/ Before Sunrise', '/ 情留半天(港)  /  爱在黎明破晓时(台)', '理查德·林克莱特 Richard Linklater', '伊桑·霍克 Ethan Hawke ...', '1995', '美国 奥地利 瑞士', '剧情 爱情', '8.8', '303607人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p452583667.jpg');
INSERT INTO `testmodel_movie` VALUES ('458', '小森林 夏秋篇', '/ リトル・フォレスト 夏・秋', '/ 小森食光 / 夏秋篇(台)', '森淳一 Junichi Mori', '桥本爱 Ai Hashimoto / 三浦贵大 Takahir...', '2014', '日本', '剧情', '9.0', '205538人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2221319641.jpg');
INSERT INTO `testmodel_movie` VALUES ('459', '驯龙高手', '/ How to Train Your Dragon', '/ 驯龙记(港)', '迪恩·德布洛斯 Dean DeBlois / 克里斯·桑德斯 Chris Sanders', '...', '2010', '美国', '动画 奇幻 冒险', '8.7', '407325人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2210954024.jpg');
INSERT INTO `testmodel_movie` VALUES ('460', '侧耳倾听', '/ 耳をすませば', '/ 心之谷  /  梦幻街少女', '近藤喜文 Yoshifumi Kondo', '本名阳子 Youko Honna / 小林桂树 K...', '1995', '日本', '剧情 爱情 动画', '8.8', '235986人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p456692072.jpg');
INSERT INTO `testmodel_movie` VALUES ('461', '请以你的名字呼唤我', '/ Call Me by Your Name', '/ 以你的名字呼唤我(港 / 台)', '卢卡·瓜达尼诺 Luca Guadagnino', '艾米·汉莫 Armie Hammer / ...', '2017', '意大利 法国 巴西 美国 荷兰 德国', '剧情 爱情 同性', '8.8', '294836人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2505525050.jpg');
INSERT INTO `testmodel_movie` VALUES ('462', '红辣椒', '/ パプリカ', '/ 盗梦侦探  /  帕布莉卡', '今敏 Satoshi Kon', '林原惠美 Megumi Hayashibara / 江守彻 Toru...', '2006', '日本', '动画 悬疑 科幻 惊悚', '8.9', '193982人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p672363704.jpg');
INSERT INTO `testmodel_movie` VALUES ('463', '倩女幽魂', '', '/ 倩女幽魂(87版)  /  倩女幽魂：妖魔道', '程小东 Siu-Tung Ching', '张国荣 Leslie Cheung / 王祖贤 Joey W...', '1987', '香港', '爱情 奇幻 武侠 古装', '8.7', '371303人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2414157745.jpg');
INSERT INTO `testmodel_movie` VALUES ('464', '恐怖直播', '/ 더 테러 라이브', '/ 死亡“动”新闻(港)  /  恐怖攻击直播(台)', '金秉祐 Byeong-woo Kim', '河正宇 Jung-woo Ha / 李璟荣 Kyeong-y...', '2013', '韩国', '剧情 犯罪 悬疑', '8.7', '325728人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2016930906.jpg');
INSERT INTO `testmodel_movie` VALUES ('465', '风之谷', '/ 風の谷のナウシカ', '/ 风谷少女  /  Kaze no tani no Naushika', '宫崎骏 Hayao Miyazaki', '岛本须美 Sumi Shimamoto / 松田洋治 Y...', '1984', '日本', '动画 奇幻 冒险', '8.8', '232521人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1917567652.jpg');
INSERT INTO `testmodel_movie` VALUES ('466', '超脱', '/ Detachment', '/ 人间师格(台)', '托尼·凯耶 Tony Kaye', '艾德里安·布洛迪 Adrien Brody / 马西...', '2011', '美国', '剧情', '8.8', '239230人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1305562621.jpg');
INSERT INTO `testmodel_movie` VALUES ('467', '上帝之城', '/ Cidade de Deus', '/ 无主之城 (港)  /  无法无天 (台)', 'Kátia Lund / Fernando Meirelles', 'Alexandre Rodrigues / Lea...', '2002', '巴西 法国', '犯罪 剧情', '8.9', '192194人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p455677490.jpg');
INSERT INTO `testmodel_movie` VALUES ('468', '爱在日落黄昏时', '/ Before Sunset', '/ 日落巴黎(港)  /  爱在日落巴黎时(台)', '理查德·林克莱特 Richard Linklater', '伊桑·霍克 Ethan Hawke ...', '2004', '美国', '剧情 爱情', '8.8', '265616人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910924055.jpg');
INSERT INTO `testmodel_movie` VALUES ('469', '菊次郎的夏天', '/ 菊次郎の夏', '/ Kikujirô no natsu  /  菊次郎的夏天', '北野武 Takeshi Kitano', '北野武 Takeshi Kitano / 关口雄介 Yus...', '1999', '日本', '剧情 喜剧', '8.8', '259434人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p751835224.jpg');
INSERT INTO `testmodel_movie` VALUES ('470', '幸福终点站', '/ The Terminal', '/ 机场客运站(港)  /  航站情缘(台)', '史蒂文·斯皮尔伯格 Steven Spielberg', '汤姆·汉克斯 Tom Hanks...', '2004', '美国', '喜剧 剧情 爱情', '8.7', '293054人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p854757687.jpg');
INSERT INTO `testmodel_movie` VALUES ('471', '哈利·波特与死亡圣器(下)', '/ Harry Potter and the Deathly Hallows: Part 2', '/ 哈利波特7：死神的圣物2(港 / 台)', '大卫·叶茨 David Yates', '丹尼尔·雷德克里夫 Daniel Radcliffe...', '2011', '美国 英国', '剧情 悬疑 奇幻 冒险', '8.7', '381768人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p917846733.jpg');
INSERT INTO `testmodel_movie` VALUES ('472', '小森林 冬春篇', '/ リトル・フォレスト 冬・春', '/ 小森食光 / 冬春篇(台)', '森淳一 Junichi Mori', '桥本爱 Ai Hashimoto / 三浦贵大 Takahir...', '2015', '日本', '剧情', '9.0', '179356人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2215147728.jpg');
INSERT INTO `testmodel_movie` VALUES ('473', '杀人回忆', '/ 살인의 추억', '/ 谋杀回忆  /  杀手回忆录', '奉俊昊 Joon-ho Bong', '宋康昊 Kang-ho Song / 金相庆 Sang-kyun...', '2003', '韩国', '犯罪 剧情 悬疑 惊悚', '8.7', '284236人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p480225538.jpg');
INSERT INTO `testmodel_movie` VALUES ('474', '7号房的礼物', '/ 7번방의 선물', '/ 戆爸的礼物(港)  /  7号囚房的礼物', '李焕庆 Hwan-kyeong Lee', '柳承龙 Seung-yong Ryoo / 朴信惠 Shi...', '2013', '韩国', '剧情 喜剧 家庭', '8.8', '252963人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1816276065.jpg');
INSERT INTO `testmodel_movie` VALUES ('475', '神偷奶爸', '/ Despicable Me', '/ 卑鄙的我  /  坏蛋奖门人(港)', '皮艾尔·柯芬 Pierre Coffin / 克里斯·雷纳德 Chris Renaud', '...', '2010', '美国 法国', '喜剧 动画 冒险', '8.5', '533626人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p792776858.jpg');
INSERT INTO `testmodel_movie` VALUES ('476', '借东西的小人阿莉埃蒂', '/ 借りぐらしのアリエッティ', '/ 借物少女艾莉缇(台)  /  借东西的小矮人亚莉亚蒂(港)', '米林宏昌 Hiromasa Yonebayashi', '志田未来 Mirai Shida / 神木...', '2010', '日本', '动画 奇幻 冒险', '8.7', '287619人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p617533616.jpg');
INSERT INTO `testmodel_movie` VALUES ('477', '萤火之森', '/ 蛍火の杜へ', '/ 萤火之社  /  Hotarubi no mori e', '大森贵弘 Takahiro Omori', '佐仓绫音 Ayane Sakura / 内山昂辉 K...', '2011', '日本', '剧情 爱情 动画 奇幻', '8.8', '236487人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1272904657.jpg');
INSERT INTO `testmodel_movie` VALUES ('478', '唐伯虎点秋香', '/ 唐伯虎點秋香', '/ Flirting Scholar', '李力持 Lik-Chi Lee', '周星驰 Stephen Chow / 巩俐 Li Gong / 陈...', '1993', '香港', '喜剧 爱情 古装', '8.5', '500620人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1946455272.jpg');
INSERT INTO `testmodel_movie` VALUES ('479', '蝙蝠侠：黑暗骑士崛起', '/ The Dark Knight Rises', '/ 蝙蝠侠前传3：黑暗骑士崛起  /  黑暗骑士：黎明升起(台)', '克里斯托弗·诺兰 Christopher Nolan', '克里斯蒂安·贝尔 Christ...', '2012', '美国 英国', '剧情 动作 科幻 犯罪 惊悚', '8.7', '389135人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1706428744.jpg');
INSERT INTO `testmodel_movie` VALUES ('480', '超能陆战队', '/ Big Hero 6', '/ 大英雄联盟(港)  /  大英雄天团(台)', '唐·霍尔 Don Hall / 克里斯·威廉姆斯 Chris Williams', '斯科特...', '2014', '美国', '喜剧 动作 科幻 动画 冒险', '8.6', '523209人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2224568669.jpg');
INSERT INTO `testmodel_movie` VALUES ('481', '怪兽电力公司', '/ Monsters, Inc.', '/ 怪兽公司(港)  /  怪物公司', '彼特·道格特 Pete Docter / 大卫·斯沃曼 David Silverman', '约...', '2001', '美国', '儿童 喜剧 动画 奇幻 冒险', '8.6', '338990人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2513247938.jpg');
INSERT INTO `testmodel_movie` VALUES ('482', '岁月神偷', '/ 歲月神偷', '/ 1969太空漫游  /  Echoes Of The Rainbow', '罗启锐 Alex Law', '吴君如 Sandra Ng / 任达华 Simon Yam / 钟绍...', '2010', '香港 中国大陆', '剧情 家庭', '8.7', '378287人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p456666151.jpg');
INSERT INTO `testmodel_movie` VALUES ('483', '电锯惊魂', '/ Saw', '/ 夺魂锯(台)  /  恐惧斗室(港)', '詹姆斯·温 James Wan', '雷·沃纳尔 Leigh Whannell / 加利·艾...', '2004', '美国', '悬疑 惊悚 恐怖', '8.7', '267458人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2163771304.jpg');
INSERT INTO `testmodel_movie` VALUES ('484', '七武士', '/ 七人の侍', '/ 七侠四义(港)  /  The Seven Samurai', '黑泽明 Akira Kurosawa', '三船敏郎 Toshirô Mifune / 志村乔 ...', '1954', '日本', '动作 冒险 剧情', '9.2', '103214人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p647099823.jpg');
INSERT INTO `testmodel_movie` VALUES ('485', '谍影重重3', '/ The Bourne Ultimatum', '/ 叛谍追击3：最后通牒(港)  /  神鬼认证：最后通牒 (台)', '保罗·格林格拉斯 Paul Greengrass', '马特·达蒙 Matt Damon / ...', '2007', '美国 德国', '动作 悬疑 惊悚', '8.7', '240234人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p792223507.jpg');
INSERT INTO `testmodel_movie` VALUES ('486', '真爱至上', '/ Love Actually', '/ 爱是您，爱是我(台)  /  真的恋爱了(港)', '理查德·柯蒂斯 Richard Curtis', '休·格兰特 Hugh Grant / 柯林...', '2003', '英国 美国 法国', '喜剧 剧情 爱情', '8.6', '411900人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p475600770.jpg');
INSERT INTO `testmodel_movie` VALUES ('487', '无人知晓', '/ 誰も知らない', '/ 谁知赤子心(港)  /  无人知晓的夏日清晨(台)', '是枝裕和 Hirokazu Koreeda', '柳乐优弥 Yûya Yagira / 北浦爱...', '2004', '日本', '剧情', '9.1', '116988人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p661160053.jpg');
INSERT INTO `testmodel_movie` VALUES ('488', '疯狂原始人', '/ The Croods', '/ 古鲁家族(港 / 台)', '科克·德·米科 Kirk De Micco / 克里斯·桑德斯 Chris Sanders', '..', '2013', '美国', '喜剧 动画 冒险', '8.7', '488942人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1867084027.jpg');
INSERT INTO `testmodel_movie` VALUES ('489', '喜宴', '/ 囍宴', '/ The Wedding Banquet', '李安 Ang Lee', '赵文瑄 Winston Chao / 郎雄 Sihung Lung / 归亚...', '1993', '台湾 美国', '剧情 喜剧 爱情 同性 家庭', '8.9', '184579人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2173713676.jpg');
INSERT INTO `testmodel_movie` VALUES ('490', '英雄本色', '', '/ A Better Tomorrow  /  Gangland Boss', '吴宇森 John Woo', '周润发 Yun-Fat Chow / 狄龙 Lung Ti / 张国...', '1986', '香港', '剧情 动作 犯罪', '8.6', '254427人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2504997087.jpg');
INSERT INTO `testmodel_movie` VALUES ('491', '萤火虫之墓', '/ 火垂るの墓', '/ 再见萤火虫(港)  /  萤火挽歌', '高畑勋 Isao Takahata', '辰己努 / 白石绫乃 / 志乃原良子', '1988', '日本', '动画 剧情 战争', '8.7', '257997人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2237136718.jpg');
INSERT INTO `testmodel_movie` VALUES ('492', '东邪西毒', '/ 東邪西毒', '/ Ashes of Time', '王家卫 Kar Wai Wong', '张国荣 Leslie Cheung / 林青霞 Brigitte...', '1994', '香港 台湾', '剧情 动作 爱情 武侠 古装', '8.6', '341239人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1982176012.jpg');
INSERT INTO `testmodel_movie` VALUES ('493', '贫民窟的百万富翁', '/ Slumdog Millionaire', '/ 贫民百万富翁(台)  /  一百万零一夜(港)', '丹尼·鲍尔 Danny Boyle / 洛芙琳·坦丹 Loveleen Tandan', '戴夫...', '2008', '英国 美国', '剧情 爱情', '8.5', '479064人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2434249040.jpg');
INSERT INTO `testmodel_movie` VALUES ('494', '黑天鹅', '/ Black Swan', '/ 夺命黑天鹅  /  霸王别鹅(豆友译名)', '达伦·阿罗诺夫斯基 Darren Aronofsky', '娜塔莉·波特曼 Natalie...', '2010', '美国', '剧情 惊悚', '8.5', '525315人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p719282906.jpg');
INSERT INTO `testmodel_movie` VALUES ('495', '记忆碎片', '/ Memento', '/ 失忆  /  记忆拼图(台)', '克里斯托弗·诺兰 Christopher Nolan', '盖·皮尔斯 Guy Pearce /...', '2000', '美国', '犯罪 剧情 悬疑 惊悚', '8.6', '356278人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p641688453.jpg');
INSERT INTO `testmodel_movie` VALUES ('496', '血战钢锯岭', '/ Hacksaw Ridge', '/ 钢锯岭  /  钢铁英雄(台)', '梅尔·吉布森 Mel Gibson', '安德鲁·加菲尔德 Andrew Garfield /...', '2016', '美国 澳大利亚', '剧情 传记 历史 战争', '8.7', '442204人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2398141939.jpg');
INSERT INTO `testmodel_movie` VALUES ('497', '傲慢与偏见', '/ Pride & Prejudice', '/ 傲慢与偏见2005  /  Pride And Prejudice', '乔·怀特 Joe Wright', '凯拉·奈特莉 Keira Knightley / 马修·...', '2005', '法国 英国 美国', '剧情 爱情', '8.5', '403029人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p452005185.jpg');
INSERT INTO `testmodel_movie` VALUES ('498', '心迷宫', '', '/ 殡棺  /  The Coffin in the Mountain', '忻钰坤 Yukun Xin', '霍卫民 Weimin Huo / 王笑天 Xiaotian Wang ...', '2014', '中国大陆', '剧情 犯罪 悬疑', '8.7', '257263人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2275298525.jpg');
INSERT INTO `testmodel_movie` VALUES ('499', '时空恋旅人', '/ About Time', '/ 时空旅恋人  /  回到最爱的一天(港)', '理查德·柯蒂斯 Richard Curtis', '多姆纳尔·格里森 Domhnall Gl...', '2013', '英国', '喜剧 爱情 奇幻', '8.7', '281891人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2070153774.jpg');
INSERT INTO `testmodel_movie` VALUES ('500', '荒蛮故事', '/ Relatos salvajes', '/ 蛮荒故事  /  生命中最抓狂的小事(台)', '达米安·斯兹弗隆 Damián Szifron', '达里奥·葛兰帝内提 Darío...', '2014', '阿根廷 西班牙', '剧情 喜剧 犯罪', '8.8', '206732人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2192834364.jpg');
INSERT INTO `testmodel_movie` VALUES ('501', '纵横四海', '/ 緃横四海', '/ Once a Thief', '吴宇森 John Woo', '周润发 Yun-Fat Chow / 张国荣 Leslie Cheung...', '1991', '香港', '剧情 喜剧 动作 犯罪', '8.8', '210148人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2272146906.jpg');
INSERT INTO `testmodel_movie` VALUES ('502', '雨人', '/ Rain Man', '/ 手足情未了  /  手足情深', '巴瑞·莱文森 Barry Levinson', '达斯汀·霍夫曼 Dustin Hoffman ...', '1988', '美国', '剧情', '8.7', '256007人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p942376281.jpg');
INSERT INTO `testmodel_movie` VALUES ('503', '教父3', '/ The Godfather: Part III', '/ 教父第三集  /  教父 III', '弗朗西斯·福特·科波拉 Francis Ford Coppola', '阿尔·帕西诺 A...', '1990', '美国', '剧情 犯罪', '8.8', '178729人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2169664351.jpg');
INSERT INTO `testmodel_movie` VALUES ('504', '达拉斯买家俱乐部', '/ Dallas Buyers Club', '/ 续命枭雄(港)  /  药命俱乐部(台)', '让-马克·瓦雷 Jean-Marc Vallée', '马修·麦康纳 Matthew McCon...', '2013', '美国', '剧情 传记 同性', '8.7', '250146人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2166160837.jpg');
INSERT INTO `testmodel_movie` VALUES ('505', '玩具总动员3', '/ Toy Story 3', '/ 反斗奇兵3(港)  /  玩具的故事3', '李·昂克里奇 Lee Unkrich', '汤姆·汉克斯 Tom Hanks / 蒂姆·艾...', '2010', '美国', '喜剧 动画 奇幻 冒险', '8.8', '251368人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1283675359.jpg');
INSERT INTO `testmodel_movie` VALUES ('506', '完美的世界', '/ A Perfect World', '/ 强盗保镳', '克林特·伊斯特伍德 Clint Eastwood', '凯文·科斯特纳 Kevin Cos...', '1993', '美国', '剧情 犯罪', '9.1', '112720人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p792403691.jpg');
INSERT INTO `testmodel_movie` VALUES ('507', '卢旺达饭店', '/ Hotel Rwanda', '/ 卢安达饭店(台)', '特瑞·乔治 Terry George', '唐·钱德尔 Don Cheadle / 苏菲·奥...', '2004', '英国 南非 意大利 美国', '剧情 历史 战争', '8.9', '153883人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2159368352.jpg');
INSERT INTO `testmodel_movie` VALUES ('508', '花样年华', '/ 花樣年華', '/ In the Mood for Love', '王家卫 Kar Wai Wong', '梁朝伟 Tony Leung Chiu Wai / 张曼玉 Ma...', '2000', '香港', '剧情 爱情', '8.6', '318843人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910828286.jpg');
INSERT INTO `testmodel_movie` VALUES ('509', '海边的曼彻斯特', '/ Manchester by the Sea', '/ 情系海边之城(港)', '肯尼斯·罗纳根 Kenneth Lonergan', '卡西·阿弗莱克 Casey Affle...', '2016', '美国', '剧情 家庭', '8.6', '278136人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2496940327.jpg');
INSERT INTO `testmodel_movie` VALUES ('510', '海洋', '/ Océans', '/ Oceans  /  海洋', '雅克·贝汉 Jacques Perrin / 雅克·克鲁奥德 Jacques Cluzaud', '...', '2009', '法国 瑞士 西班牙 美国 阿联酋', '纪录片', '9.0', '113239人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p497010372.jpg');
INSERT INTO `testmodel_movie` VALUES ('511', '恋恋笔记本', '/ The Notebook', '/ 深情日记  /  写我情真', '尼克·卡索维茨 Nick Cassavetes', '瑞恩·高斯林 Ryan Gosling /...', '2004', '美国', '剧情 爱情', '8.5', '365454人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p483604864.jpg');
INSERT INTO `testmodel_movie` VALUES ('512', '虎口脱险', '/ La grande vadrouille', '/ 横冲直撞出重围(港)  /  大進擊(台)', '杰拉尔·乌里 Gérard Oury', '路易·德·菲耐斯 Louis de Funès...', '1966', '法国 英国', '喜剧 战争', '8.9', '133481人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2399597512.jpg');
INSERT INTO `testmodel_movie` VALUES ('513', '你看起来好像很好吃', '/ おまえうまそうだな', '/ 你看起来很好吃(台)  /  你看上去好像很好吃', '藤森雅也 Masaya Fujimori', '山口胜平 Kappei Yamaguchi / 爱河...', '2010', '日本', '剧情 动画 儿童', '8.8', '190939人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2511432016.jpg');
INSERT INTO `testmodel_movie` VALUES ('514', '被解救的姜戈', '/ Django Unchained', '/ 被解放的姜戈  /  决杀令(台)', '昆汀·塔伦蒂诺 Quentin Tarantino', '杰米·福克斯 Jamie Foxx /...', '2012', '美国', '剧情 动作 西部 冒险', '8.6', '335426人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1959232369.jpg');
INSERT INTO `testmodel_movie` VALUES ('515', '二十二', '', '/ Twenty Two  /  22', '郭柯 Ke Guo', '', '2015', '中国大陆', '纪录片', '8.7', '155654人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2457609817.jpg');
INSERT INTO `testmodel_movie` VALUES ('516', '头脑特工队', '/ Inside Out', '/ 玩转脑朋友(港)  /  脑筋急转弯(台)', '彼特·道格特 Pete Docter / 罗纳尔多·德尔·卡门 Ronaldo Del Carmen  &nb..', ': 彼特·道格特 Pete Docter / 罗纳尔多·德尔·卡门 Ronaldo Del Carmen  &nb...', '2015', '美国', '喜剧 动画 冒险', '8.7', '317399人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2266293606.jpg');
INSERT INTO `testmodel_movie` VALUES ('517', '三块广告牌', '/ Three Billboards Outside Ebbing, Missouri', '/ 意外(台)  /  广告牌杀人事件(港)', '马丁·麦克唐纳 Martin McDonagh', '弗兰西斯·麦克多蒙德 France...', '2017', '美国 英国', '剧情 犯罪', '8.7', '454009人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2510081688.jpg');
INSERT INTO `testmodel_movie` VALUES ('518', '无敌破坏王', '/ Wreck-It Ralph', '/ 破坏王拉尔夫  /  破坏王大冒险', '瑞奇·莫尔 Rich Moore', '约翰·C·赖利 John C. Reilly / 萨拉...', '2012', '美国', '喜剧 动画 奇幻 冒险', '8.7', '285344人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1735642656.jpg');
INSERT INTO `testmodel_movie` VALUES ('519', '雨中曲', '/ Singin\' in the Rain', '/ 雨中情  /  万花嬉春', '斯坦利·多南 Stanley Donen / 吉恩·凯利 Gene Kelly', '吉恩·...', '1952', '美国', '喜剧 歌舞 爱情', '9.0', '118458人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1612355875.jpg');
INSERT INTO `testmodel_movie` VALUES ('520', '冰川时代', '/ Ice Age', '/ 冰河世纪  /  冰原历险记', '卡洛斯·沙尔丹哈 Carlos Saldanha / 克里斯·韦奇 Chris Wedge', '..', '2002', '美国', '喜剧 动画 冒险', '8.5', '357273人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1910895719.jpg');
INSERT INTO `testmodel_movie` VALUES ('521', '你的名字。', '/ 君の名は。', '/ 你的名字  /  君之名', '新海诚 Makoto Shinkai', '神木隆之介 Ryûnosuke Kamiki / 上...', '2016', '日本', '剧情 爱情 动画', '8.4', '693112人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2395733377.jpg');
INSERT INTO `testmodel_movie` VALUES ('522', '燃情岁月', '/ Legends of the Fall', '/ 秋日传奇  /  真爱一世情(台)', '爱德华·兹威克 Edward Zwick', '布拉德·皮特 Brad Pitt / 安东...', '1994', '美国', '剧情 爱情 战争 西部', '8.8', '177311人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1023654037.jpg');
INSERT INTO `testmodel_movie` VALUES ('523', '我是山姆', '/ I Am Sam', '/ 不一样的爸爸(港)  /  他不笨，他是我爸爸(台)', '杰茜·尼尔森 Jessie Nelson', 'Sean Penn / Dakota Fanning / Mi...', '2001', '美国', '剧情 家庭', '8.9', '141473人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p652417775.jpg');
INSERT INTO `testmodel_movie` VALUES ('524', '爆裂鼓手', '/ Whiplash', '/ 鼓动真我(港)  /  进击的鼓手(台)', '达米恩·查泽雷 Damien Chazelle', '迈尔斯·特勒 Miles Teller /...', '2014', '美国', '剧情 音乐', '8.6', '307368人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2220776342.jpg');
INSERT INTO `testmodel_movie` VALUES ('525', '人工智能', '/ Artificial Intelligence: AI', '/ AI人工智慧', '史蒂文·斯皮尔伯格 Steven Spielberg', '海利·乔·奥斯蒙 Haley...', '2001', '美国', '冒险 剧情 科幻', '8.6', '246027人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p792257137.jpg');
INSERT INTO `testmodel_movie` VALUES ('526', '未麻的部屋', '/ Perfect Blue', '/ 蓝色的恐惧  /  蓝色恐惧', '今敏 Satoshi Kon', '岩男润子 Junko Iwao / 松本梨香 Rica Matsu...', '1997', '日本', '动画 奇幻 惊悚', '8.9', '135959人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1351050722.jpg');
INSERT INTO `testmodel_movie` VALUES ('527', '穿越时空的少女', '/ 時をかける少女', '/ 跳跃吧！时空少女(台)  /  Toki o kakeru shôjo', '细田守 Mamoru Hosoda', '仲里依纱 Riisa Naka / 石田卓也 Takuya...', '2006', '日本', '剧情 爱情 科幻 动画', '8.6', '234928人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2079334286.jpg');
INSERT INTO `testmodel_movie` VALUES ('528', '魂断蓝桥', '/ Waterloo Bridge', '/ 滑铁卢桥  /  断桥残梦', '茂文·勒鲁瓦 Mervyn LeRoy', '费雯·丽 Vivien Leigh / 罗伯特·...', '1940', '美国', '剧情 爱情 战争', '8.8', '157831人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2351134499.jpg');
INSERT INTO `testmodel_movie` VALUES ('529', '一个叫欧维的男人决定去死', '/ En man som heter Ove', '/ 明天别再来敲门(台)  /  想死冇咁易(港)', '汉内斯·赫尔姆 Hannes Holm', '罗夫·拉斯加德 Rolf Lassgård...', '2015', '瑞典', '剧情', '8.8', '180185人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2406624993.jpg');
INSERT INTO `testmodel_movie` VALUES ('530', '模仿游戏', '/ The Imitation Game', '/ 解码游戏(港)  /  模拟游戏', '莫滕·泰杜姆 Morten Tyldum', '本尼迪克特·康伯巴奇 Benedict C...', '2014', '英国 美国', '剧情 传记 战争 同性', '8.6', '334751人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2255040492.jpg');
INSERT INTO `testmodel_movie` VALUES ('531', '猜火车', '/ Trainspotting', '/ 迷幻列车(港)  /  定位的火车', '丹尼·博伊尔 Danny Boyle', '伊万·麦克格雷格 Ewan McGregor / ...', '1996', '英国', '剧情 犯罪', '8.5', '296484人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p513567548.jpg');
INSERT INTO `testmodel_movie` VALUES ('532', '房间', '/ Room', '/ 不存在的房间(台)  /  抖室(港)', '伦尼·阿伯拉罕森 Lenny Abrahamson', '布丽·拉尔森 Brie Larson...', '2015', '爱尔兰 加拿大 英国 美国', '剧情 家庭', '8.8', '214437人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2259715855.jpg');
INSERT INTO `testmodel_movie` VALUES ('533', '忠犬八公物语', '/ ハチ公物語', '/ 八千公物语  /  阿八的故事', 'Seijirô Kôyama', '山本圭 Kei Yamamoto / 井川比佐志 Hisa...', '1987', '日本', '剧情', '9.1', '88489人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1576418852.jpg');
INSERT INTO `testmodel_movie` VALUES ('534', '恐怖游轮', '/ Triangle', '/ 汪洋血迷宮(台)  /  轮回三角', '克里斯托弗·史密斯 Christopher Smith', '梅利莎·乔治 Melissa ...', '2009', '英国 澳大利亚', '剧情 悬疑 惊悚', '8.4', '432107人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p462470694.jpg');
INSERT INTO `testmodel_movie` VALUES ('535', '罗生门', '/ 羅生門', '/ Rashomon', '黑泽明 Akira Kurosawa', '三船敏郎 Toshirô Mifune / 千秋实 ...', '1950', '日本', '犯罪 剧情 悬疑', '8.7', '165742人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1864872647.jpg');
INSERT INTO `testmodel_movie` VALUES ('536', '完美陌生人', '/ Perfetti sconosciuti', '/ 完美谎情(港)  /  波动的信息分享', '保罗·格诺维瑟 Paolo Genovese', '马可·贾利尼 Marco Giallini ...', '2016', '意大利', '剧情 喜剧', '8.5', '313698人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2522331945.jpg');
INSERT INTO `testmodel_movie` VALUES ('537', '魔女宅急便', '/ 魔女の宅急便', '/ 魔女琪琪(台)  /  小魔女限时专送', '宫崎骏 Hayao Miyazaki', '高山南 Minami Takayama / 佐久间玲 Re...', '1989', '日本', '动画 奇幻 冒险', '8.6', '260913人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p456676352.jpg');
INSERT INTO `testmodel_movie` VALUES ('538', '阿飞正传', '/ 阿飛正傳', '/ Days of Being Wild', '王家卫 Kar Wai Wong', '张国荣 Leslie Cheung / 张曼玉 Maggie C...', '1990', '香港', '犯罪 剧情 爱情', '8.5', '278559人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2525770523.jpg');
INSERT INTO `testmodel_movie` VALUES ('539', '香水', '/ Perfume: The Story of a Murderer', '/ 香水：一个杀人犯的故事  /  香水：一个谋杀犯的故事', '汤姆·提克威 Tom Tykwer', '本·卫肖 Ben Whishaw / 艾伦·瑞克...', '2006', '德国 法国 西班牙 美国', '剧情 犯罪 奇幻', '8.5', '345815人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p470006658.jpg');
INSERT INTO `testmodel_movie` VALUES ('540', '哪吒闹海', '', '/ Prince Nezha\'s Triumph Against Dragon King  /  Nezha nao hai', '严定宪 Dingxian Yan / 王树忱 Shuchen Wang', '梁正晖 Zhenghui ...', '1979', '中国大陆', '冒险 动画 奇幻', '8.9', '113181人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2516566783.jpg');
INSERT INTO `testmodel_movie` VALUES ('541', '浪潮', '/ Die Welle', '/ 恶魔教室(台)  /  白恤暴潮(港)', '丹尼斯·甘塞尔 Dennis Gansel', '尤尔根·沃格尔 Jürgen Vogel ...', '2008', '德国', '剧情 惊悚', '8.7', '165881人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1344888983.jpg');
INSERT INTO `testmodel_movie` VALUES ('542', '黑客帝国3：矩阵革命', '/ The Matrix Revolutions', '/ 骇客任务完结篇：最后战役  /  廿二世纪杀人网络3：惊变世纪', 'Andy Wachowski / Larry Wachowski', '基努·里维斯 Keanu Reeves...', '2003', '美国 澳大利亚', '动作 科幻', '8.6', '209826人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p443461818.jpg');
INSERT INTO `testmodel_movie` VALUES ('543', '海街日记', '/ 海街diary', '/ 海街女孩日记(港)  /  Kamakura Diary', '是枝裕和 Hirokazu Koreeda', '绫濑遥 Haruka Ayase / 长泽雅美 M...', '2015', '日本', '剧情 家庭', '8.7', '195519人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2232247487.jpg');
INSERT INTO `testmodel_movie` VALUES ('544', '朗读者', '/ The Reader', '/ 为爱朗读(台)  /  读爱(港)', '史蒂芬·戴德利 Stephen Daldry', '凯特·温丝莱特 Kate Winslet ...', '2008', '美国 德国', '剧情 爱情', '8.5', '323737人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1140984198.jpg');
INSERT INTO `testmodel_movie` VALUES ('545', '可可西里', '', '/ Kekexili: Mountain Patrol', '陆川 Chuan Lu', '多布杰 Duobujie / 张磊 Lei Zhang / 亓亮 Qi L...', '2004', '中国大陆 香港', '剧情 犯罪', '8.7', '162801人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2414771522.jpg');
INSERT INTO `testmodel_movie` VALUES ('546', '谍影重重2', '/ The Bourne Supremacy', '/ 叛谍追击2：机密圈套(港)  /  神鬼认证：神鬼疑云(台)', '保罗·格林格拉斯 Paul Greengrass', '马特·达蒙 Matt Damon / ...', '2004', '美国 德国', '动作 悬疑 惊悚', '8.6', '207325人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p667644866.jpg');
INSERT INTO `testmodel_movie` VALUES ('547', '谍影重重', '/ The Bourne Identity', '/ 叛谍追击(港)  /  神鬼认证(台)', '道格·里曼 Doug Liman', '马特·达蒙 Matt Damon / 弗兰卡·波坦...', '2002', '美国 德国 捷克', '动作 悬疑 惊悚', '8.5', '247286人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1597183981.jpg');
INSERT INTO `testmodel_movie` VALUES ('548', '战争之王', '/ Lord of War', '/ 军火之王(台 / 港)', '安德鲁·尼科尔 Andrew Niccol', '尼古拉斯·凯奇 Nicolas Cage /...', '2005', '美国 法国', '剧情 犯罪', '8.6', '214520人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p453719066.jpg');
INSERT INTO `testmodel_movie` VALUES ('549', '牯岭街少年杀人事件', '/ 牯嶺街少年殺人事件', '/ A Brighter Summer Day', '杨德昌 Edward Yang', '张震 Chen Chang / 杨静怡 Lisa Yang / 张...', '1991', '台湾', '剧情 犯罪', '8.8', '140104人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p848381236.jpg');
INSERT INTO `testmodel_movie` VALUES ('550', '地球上的星星', '/ Taare Zameen Par', '/ 心中的小星星(台)  /  每一个孩子都是特别的', '阿米尔·汗 Aamir Khan', '达席尔·萨法瑞 Darsheel Safary / 阿...', '2007', '印度', '剧情 儿童 家庭', '8.9', '112561人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1973489335.jpg');
INSERT INTO `testmodel_movie` VALUES ('551', '惊魂记', '/ Psycho', '/ 精神病患者  /  触目惊心', 'Alfred Hitchcock', 'Janet Leigh / Anthony Perkins / Vera Miles', '1960', '美国', '悬疑 惊悚 恐怖', '8.9', '112501人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1021883305.jpg');
INSERT INTO `testmodel_movie` VALUES ('552', '青蛇', '', '/ Green Snake', '徐克 Hark Tsui', '张曼玉 Maggie Cheung / 王祖贤 Joey Wang / ...', '1993', '香港', '剧情 爱情 奇幻 古装', '8.5', '287714人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p584021784.jpg');
INSERT INTO `testmodel_movie` VALUES ('553', '疯狂的石头', '', '/ Crazy Stone', '宁浩 Hao Ning', '郭涛 Tao Guo / 刘桦 Hua Liu / 连晋 Teddy Lin', '2006', '中国大陆 香港', '喜剧 犯罪', '8.4', '425233人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p712241453.jpg');
INSERT INTO `testmodel_movie` VALUES ('554', '一次别离', '/ جدایی نادر از سیمین', '/ 分居风暴(台)  /  伊朗式分居(港)', '阿斯哈·法哈蒂  Asghar Farhadi', '佩曼·莫阿迪 Peyman Moadi /...', '2011', '伊朗 法国', '剧情 家庭', '8.7', '161683人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2189835254.jpg');
INSERT INTO `testmodel_movie` VALUES ('555', '追随', '/ Following', '/ 跟踪(台)  /  致命追踪', '克里斯托弗·诺兰 Christopher Nolan', '杰里米·西奥伯德 Jeremy...', '1998', '英国', '犯罪 悬疑 惊悚', '8.9', '103091人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1150103377.jpg');
INSERT INTO `testmodel_movie` VALUES ('556', '天书奇谭', '', '/ The Legend of Sealed Book  /  Secrets of the Heavenly Book', '王树忱 Shuchen Wang / 钱运达 Yunda Qian', '丁建华 Jianhua Din...', '1983(中国大陆)', '2019(中国大陆重映)', '中国大陆', '9.1', '77408人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p842504080.jpg');
INSERT INTO `testmodel_movie` VALUES ('557', '终结者2：审判日', '/ Terminator 2: Judgment Day', '/ 终结者2  /  终结者2：末日审判', '詹姆斯·卡梅隆 James Cameron', '阿诺·施瓦辛格 Arnold Schwarz...', '1991', '美国 法国', '动作 科幻', '8.6', '187228人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910909085.jpg');
INSERT INTO `testmodel_movie` VALUES ('558', '源代码', '/ Source Code', '/ 启动原始码(台)  /  危机解密(港)', '邓肯·琼斯 Duncan Jones', '杰克·吉伦哈尔 Jake Gyllenhaal / ...', '2011', '美国 加拿大', '科幻 悬疑 惊悚', '8.4', '501004人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p988260245.jpg');
INSERT INTO `testmodel_movie` VALUES ('559', '初恋这件小事', '/ สิ่งเล็กเล็กที่เรียกว่า...รัก', '/ 初恋那件小事(港)  /  暗恋那点小事', '普特鹏·普罗萨卡·那·萨克那卡林 Puttipong Promsaka Na Sakolnakorn / 华森·波克彭..', ': 普特鹏·普罗萨卡·那·萨克那卡林 Puttipong Promsaka Na Sakolnakorn / 华森·波克彭...', '2010', '泰国', '剧情 喜剧 爱情', '8.3', '596163人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1505312273.jpg');
INSERT INTO `testmodel_movie` VALUES ('560', '步履不停', '/ 歩いても 歩いても', '/ 横山家之味(港 / 台)', '是枝裕和 Hirokazu Koreeda', '阿部宽 Hiroshi Abe / 夏川结衣 Yu...', '2008', '日本', '剧情 家庭', '8.8', '126948人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p672446737.jpg');
INSERT INTO `testmodel_movie` VALUES ('561', '小萝莉的猴神大叔', '/ Bajrangi Bhaijaan', '/ 娃娃返乡任务(台)  /  宝莱坞之钢铁奶爸(台)', '卡比尔·汗 Kabir Khan', '萨尔曼·汗 Salman Khan / 哈莎莉·马...', '2015', '印度', '剧情 喜剧 动作', '8.5', '247229人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2510956726.jpg');
INSERT INTO `testmodel_movie` VALUES ('562', '新龙门客栈', '/ 新龍門客棧', '/ New Dragon Gate Inn', '李惠民 Raymond Lee', '张曼玉 Maggie Cheung / 林青霞 Brigitte ...', '1992', '香港 中国大陆', '动作 爱情 武侠 古装', '8.5', '242493人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1421018669.jpg');
INSERT INTO `testmodel_movie` VALUES ('563', '再次出发之纽约遇见你', '/ Begin Again', '/ 再次出发  /  歌曲改变人生', '约翰·卡尼 John Carney', '凯拉·奈特莉 Keira Knightley / 马克...', '2013', '美国', '喜剧 爱情 音乐', '8.5', '230403人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2250287733.jpg');
INSERT INTO `testmodel_movie` VALUES ('564', '撞车', '/ Crash', '/ 冲击效应  /  冲撞', '保罗·哈吉斯 Paul Haggis', '桑德拉·布洛克 Sandra Bullock / ...', '2004', '美国 德国', '犯罪 剧情', '8.6', '211146人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p659411589.jpg');
INSERT INTO `testmodel_movie` VALUES ('565', '爱在午夜降临前', '/ Before Midnight', '/ 爱在午夜希腊时(台)  /  情约半生(港)', '理查德·林克莱特 Richard Linklater', '伊桑·霍克 Ethan Hawke ...', '2013', '美国 希腊', '剧情 爱情', '8.8', '155562人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2074715729.jpg');
INSERT INTO `testmodel_movie` VALUES ('566', '梦之安魂曲', '/ Requiem for a Dream', '/ 噩梦挽歌(台)  /  迷上瘾(港)', '达伦·阿伦诺夫斯基 Darren Aronofsky', '艾伦·伯斯汀 Ellen Bur...', '2000', '美国', '剧情', '8.7', '138389人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p884936202.jpg');
INSERT INTO `testmodel_movie` VALUES ('567', '海蒂和爷爷', '/ Heidi', '/ 飘零燕(港)  /  海蒂', '阿兰·葛斯彭纳 Alain Gsponer', '阿努克·斯特芬 Anuk Steffen /...', '2015', '德国 瑞士 南非', '剧情 冒险 家庭', '8.9', '83869人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2554525534.jpg');
INSERT INTO `testmodel_movie` VALUES ('568', '无耻混蛋', '/ Inglourious Basterds', '/ 恶棍特工(台)  /  希魔撞正杀人狂(港)', 'Quentin Tarantino', '布拉德·皮特 Brad Pitt / 梅拉尼·罗兰 M...', '2009', '美国 德国', '剧情 犯罪', '8.5', '277982人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p770734475.jpg');
INSERT INTO `testmodel_movie` VALUES ('569', '东京物语', '/ 東京物語', '/ 东京故事  /  Tokyo Story', '小津安二郎 Yasujirô Ozu', '笠智众 Chishû Ryû / 原节...', '1953', '日本', '剧情 家庭', '9.2', '67631人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910832390.jpg');
INSERT INTO `testmodel_movie` VALUES ('570', '城市之光', '/ City Lights', '/ City Lights: A Comedy Romance in Pantomime  /  Lichter der Großstadt', 'Charles Chaplin', '查理·卓别林 Charles Chaplin / 弗吉尼亚·...', '1931', '美国', '喜剧 剧情 爱情', '9.3', '60766人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2170238828.jpg');
INSERT INTO `testmodel_movie` VALUES ('571', '绿里奇迹', '/ The Green Mile', '/ 绿色奇迹(台)  /  绿色英里', 'Frank Darabont', '汤姆·汉克斯 Tom Hanks / 大卫·摩斯 David M...', '1999', '美国', '犯罪 剧情 奇幻 悬疑', '8.7', '136746人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p767586451.jpg');
INSERT INTO `testmodel_movie` VALUES ('572', '彗星来的那一夜', '/ Coherence', '/ 相干性  /  相干效应', '詹姆斯·沃德·布柯特 James Ward Byrkit', '艾米丽·芭尔多尼 Em...', '2013', '美国 英国', '科幻 悬疑 惊悚', '8.5', '255805人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2187896711.jpg');
INSERT INTO `testmodel_movie` VALUES ('573', '血钻', '/ Blood Diamond', '/ 血腥钻石  /  滴血钻石', '爱德华·兹威克 Edward Zwick', '莱昂纳多·迪卡普里奥 Leonardo ...', '2006', '美国 德国', '剧情 惊悚 冒险', '8.6', '180670人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1244017073.jpg');
INSERT INTO `testmodel_movie` VALUES ('574', '2001太空漫游', '/ 2001: A Space Odyssey', '/ 2001：星际漫游  /  2001：太空奥德赛', '斯坦利·库布里克 Stanley Kubrick', '凯尔·杜拉 Keir Dullea / ...', '1968', '英国 美国', '科幻 惊悚 冒险', '8.7', '137512人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p792189453.jpg');
INSERT INTO `testmodel_movie` VALUES ('575', '这个男人来自地球', '/ The Man from Earth', '/ 地球不死人(港)  /  这个人来自洞穴', '理查德·沙因克曼 Richard Schenkman', '大卫·李·史密斯 David ...', '2007', '美国', '剧情 科幻', '8.5', '234345人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p513303986.jpg');
INSERT INTO `testmodel_movie` VALUES ('576', 'E.T. 外星人', '/ E.T.: The Extra-Terrestrial', '/ 外星人E.T.  /  外星人', 'Steven Spielberg', 'Henry Thomas / Dee Wallace / Robert MacNa...', '1982', '美国', '剧情 科幻', '8.5', '200651人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p984732992.jpg');
INSERT INTO `testmodel_movie` VALUES ('577', '末路狂花', '/ Thelma & Louise', '/ 塞尔玛与路易丝  /  末路狂花', '雷德利·斯科特 Ridley Scott', '吉娜·戴维斯 Geena Davis / 苏...', '1991', '美国 法国', '犯罪 剧情 惊悚', '8.7', '131196人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p794583044.jpg');
INSERT INTO `testmodel_movie` VALUES ('578', '聚焦', '/ Spotlight', '/ 焦点追击(港)  /  惊爆焦点(台)', '托马斯·麦卡锡 Thomas McCarthy', '马克·鲁弗洛 Mark Ruffalo /...', '2015', '美国', '剧情 传记', '8.8', '163955人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2263822658.jpg');
INSERT INTO `testmodel_movie` VALUES ('579', '功夫', '', '/ 功夫3D  /  Kung Fu Hustle', '周星驰 Stephen Chow', '周星驰 Stephen Chow / 元秋 Qiu Yuen / ...', '2004', '中国大陆 香港', '动作 喜剧 犯罪 奇幻', '8.3', '415288人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2219011938.jpg');
INSERT INTO `testmodel_movie` VALUES ('580', '勇闯夺命岛', '/ The Rock', '/ 石破天惊  /  绝地任务', '迈克尔·贝 Michael Bay', '肖恩·康纳利 Sean Connery / 尼古拉...', '1996', '美国', '动作 冒险', '8.6', '174159人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p636048104.jpg');
INSERT INTO `testmodel_movie` VALUES ('581', '变脸', '/ Face/Off', '/ 夺面双雄', '吴宇森 John Woo', '约翰·特拉沃尔塔 John Travolta / 尼古拉斯...', '1997', '美国', '动作 科幻 犯罪 惊悚', '8.4', '261441人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2173855883.jpg');
INSERT INTO `testmodel_movie` VALUES ('582', '发条橙', '/ A Clockwork Orange', '/ 发条桔子  /  发条橙子', 'Stanley Kubrick', 'Malcolm McDowell / Patrick Magee / Michael...', '1971', '英国 美国', '犯罪 剧情 科幻', '8.5', '227518人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p529908155.jpg');
INSERT INTO `testmodel_movie` VALUES ('583', '黄金三镖客', '/ Il buono, il brutto, il cattivo.', '/ 好·坏·丑  /  独行侠决斗地狱门(港)', 'Sergio Leone', 'Clint Eastwood / Eli Wallach / Lee Van Cleef', '1966', '意大利 西班牙 西德', '冒险 西部', '9.1', '67169人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2101693489.jpg');
INSERT INTO `testmodel_movie` VALUES ('584', '黑鹰坠落', '/ Black Hawk Down', '/ 黑鹰降落  /  黑鹰计划', '雷德利·斯科特 Ridley Scott', '乔什·哈奈特 Josh Hartnett / ...', '2001', '美国', '动作 历史 战争', '8.6', '158116人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910900710.jpg');
INSERT INTO `testmodel_movie` VALUES ('585', '秒速5厘米', '/ 秒速5センチメートル', '/ 秒速五厘米  /  秒速5公分', '新海诚 Makoto Shinkai', '水桥研二 Kenji Mizuhashi / 近藤好美 ...', '2007', '日本', '动画 剧情 爱情', '8.3', '389054人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p982896012.jpg');
INSERT INTO `testmodel_movie` VALUES ('586', '非常嫌疑犯', '/ The Usual Suspects', '/ 刺激惊爆点(台)  /  普通嫌疑犯', '布莱恩·辛格 Bryan Singer', '史蒂芬·鲍德温 Stephen Baldwin /...', '1995', '德国 美国', '剧情 犯罪 悬疑 惊悚', '8.6', '153452人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2537319495.jpg');
INSERT INTO `testmodel_movie` VALUES ('587', '我爱你', '/ 그대를 사랑합니다', '/ 爱你  /  爱，是一生相伴(台)', '秋昌民 Chang-min Choo', '宋在河 Jae-ho Song / 李顺载 Soon-jae...', '2011', '韩国', '剧情 爱情', '9.0', '79039人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1075591188.jpg');
INSERT INTO `testmodel_movie` VALUES ('588', '卡萨布兰卡', '/ Casablanca', '/ 北非谍影(港)  /  卡萨布兰卡', '迈克尔·柯蒂兹 Michael Curtiz', '亨弗莱·鲍嘉 Humphrey Bogart...', '1942', '美国', '剧情 爱情 战争', '8.6', '153232人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2189265379.jpg');
INSERT INTO `testmodel_movie` VALUES ('589', '国王的演讲', '/ The King\'s Speech', '/ 皇上无话儿(港)  /  王者之声：宣战时刻(台)', '汤姆·霍珀 Tom Hooper', '柯林·菲尔斯 Colin Firth / 杰弗里·...', '2010', '英国 澳大利亚 美国', '剧情 传记 历史', '8.4', '417882人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p768879237.jpg');
INSERT INTO `testmodel_movie` VALUES ('590', '千钧一发', '/ Gattaca', '/ 变种异煞  /  自然人', '安德鲁·尼科尔 Andrew Niccol', '伊桑·霍克 Ethan Hawke / 乌玛...', '1997', '美国', '剧情 科幻 惊悚', '8.7', '121006人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2195672555.jpg');
INSERT INTO `testmodel_movie` VALUES ('591', '奇迹男孩', '/ Wonder', '/ 奇迹', '斯蒂芬·卓博斯基 Stephen Chbosky', '雅各布·特伦布莱 Jacob Tr...', '2017', '美国 香港', '剧情 儿童 家庭', '8.6', '290972人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2507709428.jpg');
INSERT INTO `testmodel_movie` VALUES ('592', '疯狂的麦克斯4：狂暴之路', '/ Mad Max: Fury Road', '/ 末日先锋：战甲飞车(港)  /  疯狂麦斯：愤怒道(台)', '乔治·米勒 George Miller', '汤姆·哈迪 Tom Hardy / 查理兹·塞...', '2015', '澳大利亚 美国', '动作 科幻 冒险', '8.6', '273382人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2236181653.jpg');
INSERT INTO `testmodel_movie` VALUES ('593', '遗愿清单', '/ The Bucket List', '/ 玩转身前事(港)  /  一路玩到挂(台)', '罗伯·莱纳 Rob Reiner', '杰克·尼科尔森 Jack Nicholson / 摩根...', '2007', '美国', '冒险 喜剧 剧情', '8.6', '175650人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p708613284.jpg');
INSERT INTO `testmodel_movie` VALUES ('594', '美国丽人', '/ American Beauty', '/ 美丽有罪(港)  /  美国心·玫瑰情(台)', '萨姆·门德斯 Sam Mendes', '凯文·史派西 Kevin Spacey / 安妮特...', '1999', '美国', '剧情 爱情 家庭', '8.5', '227594人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p571671715.jpg');
INSERT INTO `testmodel_movie` VALUES ('595', '驴得水', '', '/ Mr. Donkey', '周申 Shen Zhou / 刘露 Lu Liu', '任素汐 Suxi Ren / 大力 Da Li ...', '2016', '中国大陆', '剧情 喜剧', '8.3', '465068人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2393044761.jpg');
INSERT INTO `testmodel_movie` VALUES ('596', '荒岛余生', '/ Cast Away', '/ 浩劫重生(台)  /  劫后重生(港)', '罗伯特·泽米吉斯 Robert Zemeckis', '汤姆·汉克斯 Tom Hanks / ...', '2000', '美国', '冒险 剧情', '8.5', '174738人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2207673534.jpg');
INSERT INTO `testmodel_movie` VALUES ('597', '碧海蓝天', '/ Le grand bleu', '/ 碧海情深  /  夜海倾情', 'Luc Besson', '让-马克·巴尔 Jean-Marc Barr / 让·雷诺 Jean Re...', '1988', '法国 美国 意大利', '剧情 爱情', '8.7', '120388人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p455724599.jpg');
INSERT INTO `testmodel_movie` VALUES ('598', '枪火', '/ 鎗火', '/ The Mission', '杜琪峰 Johnnie To', '吴镇宇 Francis Ng / 任达华 Simon Yam / ...', '1999', '香港', '剧情 动作 犯罪', '8.7', '127231人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1538646661.jpg');
INSERT INTO `testmodel_movie` VALUES ('599', '四个春天', '', '/ Four Springs', '陆庆屹 Lu Qing Yi', '陆运坤 / 李桂贤', '2017', '中国大陆', '纪录片 家庭', '8.9', '75386人评价', 'https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540578887.jpg');
INSERT INTO `testmodel_movie` VALUES ('600', '新世界', '/ 신세계', '/ 暗黑新世界(台)  /  New World', '朴勋政 Hoon-jung Park', '李政宰 Jung-Jae Lee / 崔岷植 Min-sik...', '2013', '韩国', '剧情 犯罪', '8.7', '127889人评价', 'https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2507486724.jpg');
